---
flavours:
  test:
    description: default flavour
    distributions:
      ros1:
        root_packages:
          - test_meta
      ros2:
        root_packages:
          - rclcpp
          - rclpy

os:
  ubuntu:
    - jammy

common:
  organization: toydistro
  apt_repo: s3://locus-toydistro
  apt_region: us-east-1
  docker_registry: https://084758475884.dkr.ecr.us-east-1.amazonaws.com/locus-toydistro
  # C++17 is the default, but may be overridden on a package-by-package basis.
  cxx_standard: 17
  cxx_flags:
    - -O3
    - -g
    - -march=haswell
    # Needed for gator and geometric_shapes due to non-standard literal Q used in boost::math
    - -fext-numeric-literals
    - -DBOOST_BIND_GLOBAL_PLACEHOLDERS
    - -DBOOST_ALLOW_DEPRECATED_HEADERS
  cloudfront_distribution_id: E3MLX3ENEGCWZZ
  testing_flavour: test
  build_flavour: test
  default_build_depends:
    - build-essential
    - cmake
    - debhelper
    - fakeroot
  python_version: '3'
  distributions:
    ros1:
      compat_catkin_tools: True
      env:
        ROS_VERSION: 1
      upstream:
        name: noetic
        url: https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
      os: []
    ros2:
      env:
        ROS_VERSION: 2
      upstream:
        name: iron
        url: https://raw.githubusercontent.com/ros/rosdistro/master/index.yaml
      underlays:
        - ros1
      os:
        - jammy
